env:
  global:
    - PREFIX="/tmp/usr"

matrix:
  include:
    - os: linux
      dist: trusty
      language: generic
      sudo: false
      compiler: gcc
      env: CFLAGS="-O3 -Wall -Wextra" CXXFLAGS="-O3 -Wall -Wextra"
    - os: linux
      dist: trusty
      language: generic
      sudo: required
      compiler: gcc
      env: CFLAGS="-O3 -Wall -Wextra" CXXFLAGS="-O3 -Wall -Wextra" CONFIGURE="--target=i686-linux-gnu"
    - os: linux
      dist: trusty
      language: generic
      sudo: false
      compiler: clang
      env: CFLAGS="-O3 -Wall -Wextra" CXXFLAGS="-O3 -Wall -Wextra"
    - os: linux
      dist: trusty
      language: generic
      sudo: required
      compiler: clang
      env: CFLAGS="-O3 -Wall -Wextra" CXXFLAGS="-O3 -Wall -Wextra" CONFIGURE="--target=i686-linux-gnu"
    - os: osx
      compiler: gcc
      env: CFLAGS="-O3 -Wall -Wextra" CXXFLAGS="-O3 -Wall -Wextra"
      osx_image: xcode7.3
    - os: osx
      compiler: clang
      env: CFLAGS="-O3 -Wall -Wextra" CXXFLAGS="-O3 -Wall -Wextra"
      osx_image: xcode7.3

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#ArchC"
    on_success: change
    on_failure: always
    on_start: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ce13c79f5cdcf0e6788e
    on_success: change
    on_failure: always
    on_start: false

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CONFIGURE" == "--target=i686-linux-gnu" ] ; then sudo apt-get install -y gcc-multilib g++-multilib; fi
  - uname -a
  - env
  - export PATH="${PREFIX}/bin:${PATH}"
  - export LD_LIBRARY_PATH="${PREFIX}/lib:${LD_LIBRARY_PATH}"
  - export PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}"

install:
  - autoreconf -vif
  - ./configure --prefix=$PREFIX $CONFIGURE
  - make -j3

before_script:


script:
  - make check
  - make install
  - pkg-config systemc

after_success:


after_failure:


after_script:


before_deployment:


deployment:


after_deployment:


before_deploy:
  - ${TRAVIS_BUILD_DIR}/.travis/package.sh

deploy:
  - provider: bintray
    user: tiagofalcao
    key:
      secure: "cueydyXbTEtLyhWKtb+gmpIJZyPDUdGzN7l2Ikxih0GwVuaC/xPZI4FsrI6LjjTyTIERCUPwxSJDgZaUrAQwGhpH+VjMCNTKry/vvSA4ztbJQYR/lxr5gNsiuJJrWgfm9l8l+H/FlvB3am+/dN2Q36OSH2Z4mL2MRONkaIcLGDs="
    file: ${TRAVIS_BUILD_DIR}/.travis/bintray.json
    skip_cleanup: true
    on:
      repo: ArchC/SystemC
      branch: master
      condition: -f ${TRAVIS_BUILD_DIR}/.travis/bintray.json
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: QU7LCRSnW0Xgy66EwZ0ja1dFwoHrQ2rpzg4oZVka6ynYb26mtF2MaigEkS/2gmxgYHGnX7rplPtPevZJ1EnqInp7ICEDTRSVx7UHZvNlaC0R8rCNLE5iPC4EeDedpvVlIhD7r3qN60cdMKfWJHDW0V38s/uXE36nMCoH8tUsmUc=
    file: "$(cat ${TRAVIS_BUILD_DIR}/.travis/github-releases.txt)"
    on:
      repo: ArchC/SystemC
      tags: true
      condition: -f "${TRAVIS_BUILD_DIR}/.travis/github-releases.txt"

after_deploy:

